---
# This user will run administrative tasks (and also host
# support files if we deem so)
admin_user: chester
admin_user_key: https://github.com/chesterbr.keys

# geerlingguy.security options
security_sudoers_passwordless: "{{ admin_user }}"
security_autoupdate_enabled: true

# Blog options
blog_checkout_dir: /home/chester/chester.me/source
blog_public_dir: /home/chester/chester.me/www

# Cruzalinhas options
cruzalinhas_checkout_dir: /home/chester/cruzalinhas/source
cruzalinhas_download_sptrans_script: /home/chester/cruzalinhas/download_sptrans_gtfs.py
cruzalinhas_selenium_jar: /home/chester/cruzalinhas/selenium.jar
sptrans_download_dir: '/tmp/sptrans'
sptrans_gtfs_filename: '/home/chester/cruzalinhas/source/public/gtfs-sptrans.zip'

# Toronto Transit for Pebble options
totransit_checkout_dir: /home/chester/totransit/source
totransit_app_dir: /home/chester/totransit/source/server
