---
# This user will run administrative tasks (and also host
# support files if we deem so)
admin_user: chester
admin_user_key: https://github.com/chesterbr.keys
admin_email: cd@pobox.com

# Ansible needs to use Python 2.7
ansible_python_interpreter: /usr/bin/python2.7

# Basic nginx configuration: disable default site, add chester.me and redirects
nginx_sites:
  - server:
      listen: 80 default_server
      file_name: default
      server_name: _
      return: 444

# Blog options
blog_checkout_dir: /home/chester/chester.me/source
blog_public_dir: /home/chester/chester.me/www

# Cruzalinhas options
cruzalinhas_checkout_dir: /home/chester/cruzalinhas/source
cruzalinhas_download_sptrans_script: /home/chester/cruzalinhas/download_sptrans_gtfs.py
cruzalinhas_selenium_jar: /home/chester/cruzalinhas/selenium.jar
cruzalinhas_geckodriver_url: https://github.com/mozilla/geckodriver/releases/download/v0.11.1/geckodriver-v0.11.1-linux64.tar.gz
sptrans_download_dir: '/tmp/sptrans'
sptrans_gtfs_filename: '/home/chester/cruzalinhas/source/public/gtfs-sptrans.zip'

# Toronto Transit for Pebble options
totransit_checkout_dir: /home/chester/totransit/source
totransit_app_dir: /home/chester/totransit/source/server
