---
# This user will run administrative tasks (and also host
# support files if we deem so)
admin_user: chester
admin_user_key: https://github.com/chesterbr.keys

# Ansible needs to use Python 2.7
ansible_python_interpreter: /usr/bin/python2.7

# Basic nginx configuration: disable default site, add chester.me and redirects
nginx_sites:
  - server:
      listen: 80 default_server
      file_name: default
      server_name: _
      return: 444
  - server:
      file_name: chester.me
      root: "{{ blog_public_dir }}"
      server_name: chester.me dev.chester.me
  - server:
      file_name: redirects.chester.me
      server_name: www.chester.me m.chester.me chester.blog.br www.chester.blog.br
      return: 301 $scheme://chester.me$request_uri
  - server:
      file_name: cruzalinhas.com
      root: "{{ cruzalinhas_checkout_dir }}/public"
      server_name: cruzalinhas.com dev.cruzalinhas.com
      location1: { name: '~ .*', proxy_pass: 'http://cruzalinhas_rails' }
  - server:
      file_name: totransit.chester.me
      root: "{{ totransit_app_dir }}/public"
      server_name: totransit.chester.me dev.totransit.chester.me
      location1: { name: '~ .*', proxy_pass: 'http://totransit_rails' }
  - server:
      file_name: redirects.cruzalinhas.com
      server_name: www.cruzalinhas.com www.cruzalinhas.com.br cruzalinhas.com.br
      return: 301 $scheme://cruzalinhas.com$request_uri



# Blog options
blog_checkout_dir: /home/chester/chester.me/source
blog_public_dir: /home/chester/chester.me/www

# Cruzalinhas options
cruzalinhas_checkout_dir: /home/chester/cruzalinhas/source
cruzalinhas_download_sptrans_script: /home/chester/cruzalinhas/download_sptrans_gtfs.py
cruzalinhas_selenium_jar: /home/chester/cruzalinhas/selenium.jar
sptrans_download_dir: '/tmp/sptrans'
sptrans_gtfs_filename: '/home/chester/cruzalinhas/source/public/gtfs-sptrans.zip'

# Toronto Transit for Pebble options
totransit_checkout_dir: /home/chester/totransit/source
totransit_app_dir: /home/chester/totransit/source/server
