# The playbook is idempotent(*), although it takes some time to check
# things. If you just want to publish the latest master of the blog,
# use the publish_blog tag
#
# (*) It *does* rebuild the nginx config, but does so without affecting
#     the site. I may poke into bennojoy.nginx or even provide my own
#     role to avoid that in the future.
---
- hosts: all
  remote_user: "{{ admin_user }}"

# SETUP

  roles:
    - role: chesterbr.vault
    - role: chesterbr.nginx
    - role: chesterbr.ruby
      ruby_version: 2.2.2
      bundler_version: 1.10.5
      ruby_user: "{{ admin_user }}"

  tasks:
    - name: Add legacy redirects to blog configuration
      become: yes
      lineinfile: dest="/etc/nginx/sites-available/chester.me" line="{{ item }}" insertafter="^ *server_name.*chester.me"
      notify:
        - reload nginx
      with_items:
        - location ~ ^/m/(.*)$ { rewrite ^(.*)$ http://m.chester.me/$1 redirect; }
        - location ~ ^/200(.)(..)\.html$ { rewrite ^(.*)$ /archives/200$1/$2/ redirect; }
        - location ~ ^/micros.html?$ { rewrite ^(.*)$ /micros redirect; }
        - location ~ ^/software.html?$ { rewrite ^(.*)$ /archives/category/portfolio redirect; }
        - location ~ ^/programas.html?$ { rewrite ^(.*)$ /archives/category/portfolio redirect; }
        - location ~ ^/estadio.html?$ { rewrite ^(.*)$ /estadio redirect; }
        - location ~ ^/micros.antigos.html?$ { rewrite ^(.*)$ /micros_antigos redirect; }
        - location ~ ^/mac512.html?$ { rewrite ^(.*)$ /mac512 redirect; }
        - location ~ ^/ignition.html?$ { rewrite ^(.*)$ /ignition redirect; }
        - location ~ ^/iigs.html?$ { rewrite ^(.*)$ /iigs redirect; }
        - location ~ ^/spectrumplus2.html?$ { rewrite ^(.*)$ /spectrumplus2 redirect; }
        - location ~ ^/tk85.html?$ { rewrite ^(.*)$ /tk85 redirect; }
        - location ~ ^/eyetoy.html?$ { rewrite ^(.*)$ /eyetoy redirect; }
        - location ~ ^/gibis.html?$ { rewrite ^(.*)$ /gibis redirect; }
        - location ~ ^/pinos.html?$ { rewrite ^(.*)$ /pinos redirect; }
        - location ~ ^/placas.html?$ { rewrite ^(.*)$ /placas redirect; }
        - location ~ ^/tapete.html?$ { rewrite ^(.*)$ /tapete redirect; }
        - location ~ ^/mrtversusitconsulting.html?$ { rewrite ^(.*)$ /mrtversusitconsulting redirect; }
        - location ~ ^/archives/category/software/?$ { rewrite ^(.*)$ /archives/category/portfolio redirect; }
        - location ~ ^/smsdenuncia/?$ { rewrite ^(.*)$ /smsdenuncia/SMS-Denuncia.jad redirect; }
        - location /archives/2009/04/tweet_xkcd_bookmarklet { rewrite ^(.*)$ /archives/2009/04/tweet_xkcd_bookmarklet.html redirect; }
        - location /minitruco { rewrite ^(.*)$ /archives/2006/01/mt.html redirect; }
        - location /miniTruco { rewrite ^(.*)$ /archives/2006/01/mt.html redirect; }
        - location /minitruco_en { rewrite ^(.*)$ /archives/2007/12/minitruco_free.html redirect; }
        - location /curriculum.pdf { rewrite ^(.*)$ http://www.linkedin.com/in/chesterbr redirect; }
        - location /resume.pdf { rewrite ^(.*)$ http://www.linkedin.com/in/chesterbr redirect; }
        - location /resume/? { rewrite ^(.*)$ http://www.linkedin.com/in/chesterbr redirect; }

    - name: Install prereq packages
      apt: name={{ item }} state=installed
      become: yes
      with_items:
        - git

# PUBLISH

    - name: Ensure blog repository is at latest version
      git: repo=git@github.com:chesterbr/octopress.git
           accept_hostkey=true
           dest={{ blog_checkout_dir }}
           version=master
      tags:
        - publish_blog

    - name: Ensure we have all gem dependencies for octopress
      command: bash -lc "cd {{ blog_checkout_dir }}; bundle install"
      tags:
        - publish_blog

    - name: Rebuild the blog
      command: bash -lc "cd {{ blog_checkout_dir }}; bundle exec rake generate"
      tags:
        - publish_blog

    - name: Update public dir with rebuilt files
      command: "rsync --archive --delete {{ blog_checkout_dir }}/public/ {{ blog_public_dir }}"
      tags:
        - publish_blog
      notify:
        - reload nginx
