# Configures the Raspberry Pi that handles my home automation
#
# It assumes my user has already been created by rpi_provisioning.yml

- hosts: raspberrypi
  remote_user: "{{ admin_user }}"
  become: yes
  vars:
    admin_user: chesterbr
    admin_email: cd@pobox.com
    host: tv-pi
    external_hostname: chesterbr.duckdns.org
  handlers:
  - name: restart ssh
    service: name=sshd state=restarted

  - name: restart unattended-upgrades
    service: name=unattended-upgrades state=restarted

  - name: restart lirc
    service: name=lircd state=restarted

  - name: reboot
    reboot:

  tasks:
  - name: Update packages info (if older than a couple days)
    apt: update_cache=yes cache_valid_time=7200

  - name: Install general utilities
    apt: name={{ packages }} state=present
    vars:
      packages:
        - git

  - name: Install fail2ban.
    apt: name=fail2ban state=present

  - name: Ensure fail2ban is running and enabled on boot.
    service: name=fail2ban state=started enabled=yes

  - name: Update SSH configuration to be more secure (no password/root logins).
    lineinfile:
      dest: "/etc/ssh/sshd_config"
      regexp: "{{ item.regexp }}"
      line: "{{ item.line }}"
      state: present
    with_items:
      - regexp: "^PasswordAuthentication"
        line: "PasswordAuthentication no"
      - regexp: "^PermitRootLogin"
        line: "PermitRootLogin no"
    notify: restart ssh

  # Uncomment if you don't want the local pi user (e.g., if RPI isn't physically secure)
  # - name: Drop the pi user (we don't need it and can't even use it remotely at this point)
  #   user: name={{ admin_user }} state=absent remove=yes

  - name: Install unattended upgrades package and dependencies.
    apt: name={{ packages }} state=present
    vars:
      packages:
        - unattended-upgrades
        - apt-listchanges
        - bsd-mailx

  - name: Updated unattended-upgrades config to reboot if needed,
          auto-fix, reboot time, email, etc
    lineinfile:
      dest: "/etc/apt/apt.conf.d/50unattended-upgrades"
      regexp: "{{ item.regexp }}"
      line: "{{ item.line }}"
      state: present
    with_items:
      - regexp: "(\/\/)? ?Unattended-Upgrade::AutoFixInterruptedDpkg \""
        line: Unattended-Upgrade::AutoFixInterruptedDpkg "true";
      - regexp: "(\/\/)? ?Unattended-Upgrade::MinimalSteps \""
        line: Unattended-Upgrade::MinimalSteps "true";
      - regexp: "(\/\/)? ?Unattended-Upgrade::Automatic-Reboot \""
        line: Unattended-Upgrade::Automatic-Reboot "true";
      - regexp: "(\/\/)? ?Unattended-Upgrade::Automatic-Reboot-Time \""
        line: Unattended-Upgrade::Automatic-Reboot-Time "02:00";
      - regexp: "(\/\/)? ?Unattended-Upgrade::Mail \""
        line: Unattended-Upgrade::Mail "{{ admin_email }}";
      - regexp: "(\/\/)? ?Unattended-Upgrade::MailOnlyOnError \""
        line: Unattended-Upgrade::MailOnlyOnError "false";
      - regexp: "(\/\/)? ?Unattended-Upgrade::Remove-Unused-Dependencies \""
        line: Unattended-Upgrade::Remove-Unused-Dependencies "true";
    notify: restart unattended-upgrades

  - name: (Re)configure firewall (ufw)
    tags:
      - firewall
    block:
      - apt: name=ufw state=present
      - ufw: rule=allow port={{ item }}
        with_items:
          - 22     # ssh
          - 80     # http    (mostly to generate/renew certs)
          - 443    # https   (mostly to generate/renew certs)
          - 8123   # Home Assistant
      - ufw: state=enabled policy=reject direction=incoming

  - name: Install certbot (so we can have letsencrypt ssl certificates)
    apt: name=certbot state=present

  - name: Create script that generates/renews (and copies to the right place)
          certificates as needed
    template:
      src: templates/update_and_copy_certificates.sh.j2
      dest: /root/update_and_copy_certificates.sh
      owner: root
      mode: 0700

  - name: Run the script once (so we have certificates to play with)
    command: bash -lc "/root/update_and_copy_certificates.sh"

  - name: Schedule cercertbot to rebuild the certs when needed \
          (and copy/fix perms so HomeAssistant can use them)
    cron:
      name: Update ssl certificates
      minute: 0
      hour: 4
      weekday: 0 # Sundays
      user: root
      job: /root/update_and_copy_certificates.sh

  - name: Install packages required for Bluetooth
    apt: name={{ packages }} state=present
    vars:
      packages:
        - bluetooth
        - bluez
        - bluez-firmware
        - libbluetooth-dev

  - name: Build and install RF (433Mhz) control software, then enable our user to run it
    block:
      - apt: name=wiringpi state=present
      - git:
          repo: git://github.com/ninjablocks/433Utils.git
          dest: /root/433Utils
          recursive: yes
      - command: make
        args:
          chdir: /root/433Utils/RPi_utils
      - copy:
          src: /root/433Utils/RPi_utils/{{ item }}
          dest: /usr/bin/{{ item }}
          mode: 0755
          remote_src: yes
        with_items:
          - codesend
          - RFSniffer
      - user: name="{{ admin_user }}" groups=gpio append=yes

  - name: Install and configure LIRC (infrared), using GPIO22 for output and GPIO23 for input
    block:
      - apt: name=lirc state=present
      - lineinfile:
           dest: /boot/config.txt
           regexp: "^#? ?dtoverlay="
           line: "dtoverlay=lirc-rpi,gpio_in_pin=23,gpio_out_pin=22"
           state: present
        notify: reboot
      - blockinfile:
           dest: /etc/modules
           block:
             lirc_dev
             lirc_rpi gpio_in_pin=23 gpio_out_pin=22
        notify: reboot
      - template:
          src: templates/lirc_hardware_conf.j2
          dest: /etc/lirc/hardware.conf
          owner: root
        notify: restart lirc
      - template:
          src: Sharp_LCDTV-845-039-40B0.lircd.conf.j2
          dest: /etc/lirc/lircd.conf.d/
        notify: restart lirc
