---

- name: Install the nginx packages
  become: yes
  apt: name=nginx state=present

- name: Copy the nginx configuration file
  become: yes
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf
  notify:
   - restart nginx

- name: Copy the nginx default configuration file
  become: yes
  template: src=default.conf.j2 dest=/etc/nginx/conf.d/default.conf

- name: Copy the nginx default site configuration file
  become: yes
  template: src=default.j2 dest=/etc/nginx/sites-available/default

- name: Create the link for site enabled specific configurations
  become: yes
  file: path=/etc/nginx/sites-enabled/default state=link src=/etc/nginx/sites-available/default

- name: Create the configurations for sites
  become: yes
  template: src=site.j2 dest=/etc/nginx/sites-available/{{ item['server']['file_name'] }}
  with_items: "{{ nginx_sites }}"

- name: Create the links to enable site configurations
  become: yes
  file: path=/etc/nginx/sites-enabled/{{ item['server']['file_name'] }} state=link src=/etc/nginx/sites-available/{{ item['server']['file_name'] }}
  with_items: "{{ nginx_sites }}"
  notify:
   - reload nginx

- name: Add cruzalinhas upstream to server config
  become: yes
  lineinfile: dest=/etc/nginx/sites-enabled/cruzalinhas.com insertbefore="BOF" line="upstream cruzalinhas_rails { server 127.0.0.1:3000; }"
  notify:
   - reload nginx

- name: Add totransit upstream to server config
  become: yes
  lineinfile: dest=/etc/nginx/sites-enabled/totransit.chester.me insertbefore="BOF" line="upstream totransit_rails { server 127.0.0.1:3001; }"
  notify:
   - reload nginx
