homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 43.5647
  longitude: -79.5852
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Toronto
  # Customization file
  customize: !include customize.yaml

# Show links to resources in log and frontend
introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123
http:
  ssl_certificate: /home/chesterbr/fullchain.pem
  ssl_key: /home/chesterbr/privkey.pem
  base_url: https://chesterbr.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Sensors
sensor:
  # Weather prediction
  - platform: yr

# Am I home?
device_tracker:
  - platform: bluetooth_tracker

# Text to speech
tts:
  - platform: google

switch:
  - platform: switchmate
    name: Living Room Light
    mac: !secret living_room_light_mac
    flip_on_off: true
  - platform: switchmate
    name: Bedroom Lamp
    mac: !secret bedroom_lamp_mac
    flip_on_off: true
  - platform: command_line
    switches:
      living_room_lamp:
        friendly_name: Living Room Lamp
        command_on: !secret living_room_lamp_on_command
        command_off: !secret living_room_lamp_off_command

# Google Assitant
google_assistant:
  project_id: !secret google_assistant_project_id
  api_key: !secret google_assistant_api_key
  exposed_domains:
    - switch
    - light
    - group

# Cloud
cloud:

# group: !include groups.yaml
group:
  living_room_lights:
    name: Living Room Lights
    entities:
      - switch.living_room_spot
      - switch.living_room_lamp
  bedroom_lights:
    name: Bedroom Lights
    entities:
      - switch.bedroom_lamp
#automation: !include automations.yaml
script: !include scripts.yaml

shell_command:
  tv_power: irsend SEND_ONCE Sharp_LCDTV-845-039-40B0 KEY_POWER
  tv_source_atari: '/home/chesterbr/tv_source.lua 2'
  tv_source_chromecast: '/home/chesterbr/tv_source.lua 4'
  tv_source_switch: '/home/chesterbr/tv_source.lua 5'
  tv_source_bell: '/home/chesterbr/tv_source.lua 6'

automation:
  - alias: tv_on_and_off
    trigger:
      platform: event
      event_type: ifttt_webhook_received
      event_data:
        action: tv
    condition:
      condition: template
      value_template: "{{ trigger.event.data.parameter == \"on\" or trigger.event.data.parameter == \"off\" }}"
    action:
      service: shell_command.tv_power

  - alias: tv_atari
    trigger:
      platform: event
      event_type: ifttt_webhook_received
      event_data:
        action: tv
        parameter: Atari
    action:
      service: shell_command.tv_source_atari

  - alias: tv_chromecast
    trigger:
      platform: event
      event_type: ifttt_webhook_received
      event_data:
        action: tv
        parameter: Chromecast
    action:
      service: shell_command.tv_source_chromecast

  - alias: tv_switch
    trigger:
      platform: event
      event_type: ifttt_webhook_received
      event_data:
        action: tv
        parameter: Switch
    action:
      service: shell_command.tv_source_switch

  - alias: tv_bell
    trigger:
      platform: event
      event_type: ifttt_webhook_received
      event_data:
        action: tv
        parameter: Bell
    action:
      service: shell_command.tv_source_bell
